# Generated by Django 4.2.1 on 2023-05-09 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('sent', 'Заявка отправлена'),
                            ('rejected', 'Заявка отклонена'),
                            ('accepted', 'Заявка принята'),
                        ],
                        default='sent',
                        max_length=20,
                    ),
                ),
                (
                    'from_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='friend_requests_sent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'to_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='friend_requests_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
