# Generated by Django 4.2.1 on 2023-05-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="user_id_2",
            field=models.ManyToManyField(related_name="+", to="friend.user"),
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="user_id_1",
        ),
        migrations.CreateModel(
            name="ApplicationToFriends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id_1",
                    models.ManyToManyField(related_name="+", to="friend.user"),
                ),
                (
                    "user_id_2",
                    models.ManyToManyField(related_name="+", to="friend.user"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="friendship",
            name="user_id_1",
            field=models.ManyToManyField(related_name="+", to="friend.user"),
        ),
    ]
