# Generated by Django 4.2.1 on 2023-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friend", "0002_friendship_user_id_2_remove_friendship_user_id_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
