# Generated by Django 4.2.1 on 2023-05-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friend", "0002_alter_friendrequest_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Заявка отправлена"),
                    ("rejected", "Заявка отклонена"),
                    ("accepted", "Заявка принята"),
                    ("friend", "Друзья"),
                ],
                default="sent",
                max_length=20,
            ),
        ),
    ]
